[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
numReplicas = 1
waitForHealthcheck = true

[deploy.env]
NODE_ENV = "production"

[[services]]
name = "app"
internal_port = 3000
protocol = "tcp"
waitForSearcher = true

[services.ports]
http = 3000
socket = 3001
smtp = 25
smtps = 465
submission = 587
imap = 143
imaps = 993

[database]
name = "postgres"
plan = "free"
waitForSearcher = true

[mail]
name = "mailcow" 