version: '3.8'

services:
  mailcow-nginx:
    image: mailcow/nginx:1.25
    container_name: mailcow-nginx
    restart: always
    dns:
      - 127.0.0.11
    environment:
      - TZ=${MAILCOW_TZ}
    volumes:
      - ./data/conf/nginx:/etc/nginx/conf.d:ro
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro
      - ./data/assets/ssl:/etc/ssl/mail:ro
      - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
      - ./data/conf/phpfpm/sogo-sso:/etc/sogo-sso
      - ./data/conf/phpfpm/php-fpm.d:/etc/php/8.1/fpm/pool.d
      - ./data/conf/phpfpm/php.ini:/etc/php/8.1/fpm/php.ini
      - ./data/web:/web:ro
    ports:
      - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:80"
      - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:443"
    networks:
      mailcow-network:
        aliases:
          - nginx

  mailcow-dovecot:
    image: mailcow/dovecot:1.25
    container_name: mailcow-dovecot
    restart: always
    depends_on:
      - mailcow-mysql
    dns:
      - 127.0.0.11
    environment:
      - TZ=${MAILCOW_TZ}
    volumes:
      - ./data/conf/dovecot:/etc/dovecot
      - ./data/assets/ssl:/etc/ssl/mail:ro
      - ./data/vmail:/var/vmail
      - ./data/indexes:/var/indexes
    ports:
      - "${IMAP_PORT:-143}:143"
      - "${IMAPS_PORT:-993}:993"
      - "${POP_PORT:-110}:110"
      - "${POPS_PORT:-995}:995"
    networks:
      mailcow-network:
        aliases:
          - dovecot

  mailcow-postfix:
    image: mailcow/postfix:1.25
    container_name: mailcow-postfix
    restart: always
    depends_on:
      - mailcow-mysql
    dns:
      - 127.0.0.11
    environment:
      - TZ=${MAILCOW_TZ}
    volumes:
      - ./data/conf/postfix:/opt/postfix/conf
      - ./data/assets/ssl:/etc/ssl/mail:ro
    ports:
      - "${SMTP_PORT:-25}:25"
      - "${SMTPS_PORT:-465}:465"
      - "${SUBMISSION_PORT:-587}:587"
    networks:
      mailcow-network:
        aliases:
          - postfix

  mailcow-mysql:
    image: mariadb:10.5
    container_name: mailcow-mysql
    restart: always
    dns:
      - 127.0.0.11
    environment:
      - TZ=${MAILCOW_TZ}
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    volumes:
      - ./data/db/mysql/:/var/lib/mysql/
    networks:
      mailcow-network:
        aliases:
          - mysql

networks:
  mailcow-network:
    driver: bridge 